### PR TITLE
Feature/autoload

### PR DESCRIPTION
**Pull request by doronz88**
Added an autoload feature for the symbols file for the first time. I find it really handy :)

### CODE REVIEW

**Comment by blacktop** [comment]
will this try and run before the kernelcache is done being loaded/analyzed the first time? If so I'd worry that might interferer w/ IDA's initial analysis?

**Comment by doronz88** [comment]
I also suspected that, but fortunately IDA runs the plugin entry point only after the loader has finished

**Comment by blacktop** [comment]
Trying it now and I see:
```bash
Error: Address 0xfffffff00a64f638 is not valid for this binary
Error: Address 0xfffffff00a64f67c is not valid for this binary
🎉 Symbolicated 4084 addresses 🎉
Symbolicate Plugin initialized.
IDA is analysing the input file...
You may start to explore the input file right now.
```

The errors are because I'm only loading the kernel (no KEXTs)

but it does seem weird that it runs before the plugin is done initializing? and before the kernel is done being analyzed by IDA (though that might be okay if you are correct that IDA has already loaded all the segments and also created all the functions that it's going to?

I think it runs additional analysis for example when creating funcs and determining if it is a non-returning func etc.

I'm worried that us marking it as a function and labeling it might mess w/ that and IDA might stomp on the Symbolicator symbols?  I could be wrong though as running IDA 9 on a M1 Max goes very fast so the function analysis might have already been completed before Symbolicate ran?

Also hopefully IDA is smart enough not to stomp on symbols that were applied by the user, but I could see it doing it if it wasn't expecting something like symbolication to be happening immediately after loading the bin.

**Comment by doronz88** [comment]
From my understanding that is fine. IDA in general in single threaded so since the loader always runs first then just naming the symbols should not have any bad implications (BTW, I loaded with all kexts so no errors)

**Pull request merged**
